services:

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    networks:
      - microservices-net

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge