server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone : http://eureka-server:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/api/usuarios/**
        - id: academico-service
          uri: lb://academico-service
          predicates:
            - Path=/api/academico/**
        - id: comunicacion-service
          uri: lb://comunicacion-service
          predicates:
            - Path=/api/comunicaciones/**
        - id: estudiante-service
          uri: lb://estudiante-service
          predicates:
            - Path=/api/estudiantes/**
        - id: asistencia-service
          uri: lb://asistencia-service
          predicates:
            - Path=/api/asistencia/**
        - id: evaluacion-service
          uri: lb://evaluacion-service
          predicates:
            - Path=/api/evaluaciones/**
        - id: anotacion-service
          uri: lb://anotacion-service
          predicates:
            - Path=/api/anotaciones/**
        - id: notificacion-service
          uri: lb://notificacion-service
          predicates:
            - Path=/api/notificaciones/**
        - id: reporte-service
          uri: lb://reporte-service
          predicates:
            - Path=/api/reportes/**

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970